language: node_js

node_js:
    - "9.2.0"

sudo: false

git:
    submodules: false

cache:
    directories:
        - node_modules

# before_script:
#     # Prepare for automated tests
#     - npm install
before_install:
  - npm install -g npm@latest

script:
    # Run tests
    - npm run build
    - npm test
